---
- name: Generate SSH key pair locally
  community.crypto.openssh_keypair:
    path: "{{ ssh_key }}"
    type: ed25519
  delegate_to: localhost
  become: false

- name: Add SSH public key
  ansible.posix.authorized_key:
    user: ec2-user
    key: "{{ lookup('file', ssh_key + '.pub') }}"
