---
- hosts: all
  become: yes
  vars:
    aws_account_id: "{{ account_id }}"
    ecr_registry: "{{ account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      become: true

    - name: Log in to ECR
      community.docker.docker_login:
        registry_url: "{{ ecr_registry }}"
        username: AWS
        password: "{{ ecr_password }}"

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ ecr_registry }}/my-dockerized-service:latest"
        source: pull
        force_source: yes

    - name: Run Docker container with port mapping
      community.docker.docker_container:
        name: my-container
        image: "{{ ecr_registry }}/my-dockerized-service:latest"
        state: started
        recreate: yes
        ports:
          - "80:3000"
